| sql_backup                                                                                                                                                                                                                                                                                                                                                                                                         |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| -- ============================================                                                                                                                                                                                                                                                                                                                                                                    |
| -- BACKUP DE DATOS - 2026-01-09                                                                                                                                                                                                                                                                                                                                                                                    |
| -- ============================================                                                                                                                                                                                                                                                                                                                                                                    |
|                                                                                                                                                                                                                                                                                                                                                                                                                    |
| -- CATEGORIAS                                                                                                                                                                                                                                                                                                                                                                                                      |
| INSERT INTO categorias_disponibilidad (id, categoria, nombre_es, nombre_ca, nombre_en, disponible, temporada, orden) VALUES ('014609ba-e78d-4f8c-b7fb-8e49b286c473'::uuid, 'entrantes', 'Entrantes', 'Entrants', 'Starters', true, 'todo_año', 1);                                                                                                                                                                 |
| INSERT INTO categorias_disponibilidad (id, categoria, nombre_es, nombre_ca, nombre_en, disponible, temporada, orden) VALUES ('a1026b31-e735-43f5-ba4d-ffd7e8639422'::uuid, 'platos_calientes', 'Platos Calientes', 'Plats Calents', 'Hot Dishes', true, 'todo_año', 2);                                                                                                                                            |
| INSERT INTO categorias_disponibilidad (id, categoria, nombre_es, nombre_ca, nombre_en, disponible, temporada, orden) VALUES ('6f275f92-0222-4d2a-88db-4e41fa139c52'::uuid, 'pescados', 'Pescados', 'Peixos', 'Fish', true, 'todo_año', 3);                                                                                                                                                                         |
| INSERT INTO categorias_disponibilidad (id, categoria, nombre_es, nombre_ca, nombre_en, disponible, temporada, orden) VALUES ('9c41c92b-0599-43f7-a7b9-9cebcb3d2724'::uuid, 'postres', 'Postres', 'Postres', 'Desserts', true, 'todo_año', 5);                                                                                                                                                                      |
| INSERT INTO categorias_disponibilidad (id, categoria, nombre_es, nombre_ca, nombre_en, disponible, temporada, orden) VALUES ('e838ae2b-676b-4573-b9cf-e76fa9e7c194'::uuid, 'carnes', 'Carnes', 'Carns', 'Meats', true, 'todo_año', 5);                                                                                                                                                                             |
| INSERT INTO categorias_disponibilidad (id, categoria, nombre_es, nombre_ca, nombre_en, disponible, temporada, orden) VALUES ('b3868850-6272-4dd2-a919-17b16944349f'::uuid, 'vino_blanco', 'Vinos Blancos', 'Vins Blancs', 'White Wines', true, 'todo_año', 6);                                                                                                                                                     |
| INSERT INTO categorias_disponibilidad (id, categoria, nombre_es, nombre_ca, nombre_en, disponible, temporada, orden) VALUES ('215b9e0c-8407-489c-936a-61410d19e8d8'::uuid, 'vino_tinto', 'Vinos Tintos', 'Vins Negres', 'Red Wines', true, 'todo_año', 7);                                                                                                                                                         |
| INSERT INTO categorias_disponibilidad (id, categoria, nombre_es, nombre_ca, nombre_en, disponible, temporada, orden) VALUES ('229fec95-34f4-42b6-8ecc-6a1a51f927f6'::uuid, 'cava_champagne', 'Cavas y Champagne', 'Caves i Champagne', 'Cavas & Champagne', true, 'todo_año', 8);                                                                                                                                  |
|                                                                                                                                                                                                                                                                                                                                                                                                                    |
| -- MENU ITEMS                                                                                                                                                                                                                                                                                                                                                                                                      |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('63ab78f7-5d13-4172-9dc3-c31661af6d48'::uuid, 'Zorza con Patatas', 'Zorza amb Patates', 'Zorza with Potatoes', 'carnes', 20.00, false, NULL, NULL, 1, NULL, NULL, NULL, false);                                   |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('f8eb553c-30a2-4069-a0f0-a41eca38f2f5'::uuid, 'Solomillo Ternera Blanca', 'Filet de Vedella Blanca', 'White Veal Tenderloin', 'carnes', 29.00, false, NULL, NULL, 2, NULL, NULL, NULL, true);                     |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('512d5480-c5b9-4a01-95ec-f097c1ad3ee3'::uuid, 'Chuleton Madurado', 'Txuleton Madurat', 'Aged T-Bone Steak', 'carnes', 104.00, false, NULL, NULL, 3, NULL, NULL, NULL, true);                                      |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('97a2d36b-4966-454b-b622-1d25feaab980'::uuid, 'Entrecot Madurado', 'Entrecot Madurat', 'Aged Ribeye', 'carnes', 35.00, false, NULL, NULL, 4, NULL, NULL, NULL, true);                                             |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('9a571541-1070-4454-b40b-448d41daaaa9'::uuid, 'Marqués de la Concordia', NULL, NULL, 'cava_champagne', 22.00, false, NULL, NULL, 1, NULL, NULL, NULL, true);                                                      |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('b4d4e7b2-bd93-4bd9-9502-0428c6ac4e07'::uuid, 'Juve & Camps', NULL, NULL, 'cava_champagne', 52.00, false, NULL, NULL, 2, NULL, NULL, NULL, true);                                                                 |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('616ae216-c873-4320-b4d9-ead1e7fbd7b3'::uuid, 'Moet Chandon', NULL, NULL, 'cava_champagne', 85.00, false, NULL, NULL, 3, NULL, NULL, NULL, true);                                                                 |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('6487e55a-dcbf-427f-8239-ab561a6b6796'::uuid, 'La Vinya del Refugi', NULL, NULL, 'cava_champagne', 94.00, false, NULL, NULL, 4, NULL, NULL, NULL, true);                                                          |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('9aa9982a-2b5b-43ab-b966-fb1b5071f887'::uuid, 'Taittinger', NULL, NULL, 'cava_champagne', 125.00, false, NULL, NULL, 5, NULL, NULL, NULL, true);                                                                  |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('5b065889-3944-43d1-95be-f46dcd900f2c'::uuid, 'Louis Roederer', NULL, NULL, 'cava_champagne', 125.00, false, NULL, NULL, 6, NULL, NULL, NULL, true);                                                              |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('5664399a-5efd-44a9-93c9-60efd7cb03ed'::uuid, 'Bollinger', NULL, NULL, 'cava_champagne', 120.00, false, NULL, NULL, 7, NULL, NULL, NULL, true);                                                                   |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('98b862a3-52a8-4bb8-a361-8e2c0ee2be25'::uuid, 'Empanada Gallega', 'Empanada Gallega', 'Galician Empanada', 'entrantes', 7.00, false, NULL, NULL, 1, NULL, NULL, NULL, true);                                      |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('668708fb-8b51-4bf4-97aa-6b38d336c8e4'::uuid, 'Ensalada Bonito', 'Amanida de Bonítol', 'Bonito Salad', 'entrantes', 21.00, false, NULL, NULL, 2, NULL, NULL, NULL, true);                                         |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('a7ca2e5e-1d85-49ec-a30c-5834c626d344'::uuid, 'Pulpo a Feira', 'Pop a Feira', 'Galician-Style Octopus', 'entrantes', 28.00, false, NULL, NULL, 3, NULL, NULL, NULL, true);                                        |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('fbe5e5de-fc79-4a1f-af97-38c9565f634b'::uuid, 'Anchoas 00', 'Anxoves 00', 'Premium Anchovies 00', 'entrantes', 4.00, false, NULL, 'ud', 4, NULL, NULL, NULL, true);                                               |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('dc647f56-9808-4f2e-a62c-b855b3f282e9'::uuid, 'Zamburiñas', 'Zamburiñas', 'Queen Scallops', 'entrantes', 28.00, false, NULL, NULL, 5, NULL, NULL, NULL, true);                                                    |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('534b9322-3e0f-4ee6-8505-d629351d64ca'::uuid, 'Jamón Ibérico', 'Pernil Ibèric', 'Iberian Ham', 'entrantes', 35.00, false, NULL, NULL, 6, NULL, NULL, NULL, true);                                                 |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('56c57af5-3ff1-407b-bda9-2414e93bbf7f'::uuid, 'Tirabeques', 'Pèsols Tendres', 'Snow Peas', 'entrantes', 14.00, false, NULL, NULL, 7, NULL, NULL, NULL, true);                                                     |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('20561cb5-2b34-41ff-9197-ffac4751f1b3'::uuid, 'Queso con Anchoas', 'Formatge amb Anxoves', 'Cheese with Anchovies', 'entrantes', 5.00, false, NULL, 'ud', 8, NULL, NULL, NULL, true);                             |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('a1635cb3-1926-4446-9d37-d04bc7d4f3fc'::uuid, 'Croquetas de Ibérico', 'Croquetes d''Ibèric', 'Iberian Croquettes', 'entrantes', 4.00, false, NULL, 'ud', 9, NULL, NULL, NULL, true);                              |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('6666c9a6-6e80-4d14-aabe-0786ada718d9'::uuid, 'Buñuelos', 'Bunyols', 'Fritters', 'entrantes', 4.00, false, NULL, 'ud', 10, '(Bacalao / Merluza)', '(Bacallà / Lluç)', '(Cod / Hake)', true);                      |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('555c6cf8-6775-4f31-93bf-397ee7b6f660'::uuid, 'Calamar de Potera', 'Calamar de Potera', 'Squid', 'entrantes', 30.00, false, NULL, NULL, 11, NULL, NULL, NULL, true);                                              |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('8eaf1eb7-b787-47b1-9521-a05b1a1a841e'::uuid, 'Alcachofas', 'Carxofes', 'Artichokes', 'entrantes', 9.00, false, NULL, NULL, 12, NULL, NULL, NULL, true);                                                          |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('395fb131-5723-4948-9fe3-b66bb09cb59e'::uuid, 'Angulas', 'Angules', 'Baby Eels', 'entrantes', NULL, true, NULL, NULL, 13, NULL, NULL, NULL, true);                                                                |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('4a6f601d-f3fc-4404-89a8-8a33bf7f2a86'::uuid, 'Lubina', 'Llobarro', 'Sea Bass', 'pescados', NULL, true, NULL, NULL, 1, NULL, NULL, NULL, true);                                                                   |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('5bee100a-0d88-4ec1-9db0-6e8f3b61598f'::uuid, 'Rodaballo', 'Rèmol', 'Turbot', 'pescados', NULL, true, NULL, NULL, 2, NULL, NULL, NULL, true);                                                                     |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('db5c34a3-039d-4e83-83b4-5483a4c2baa5'::uuid, 'Merluza', 'Lluç', 'Hake', 'pescados', NULL, true, NULL, NULL, 3, NULL, NULL, NULL, true);                                                                          |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('b700989c-8cd1-4bfb-852c-b4d883258de5'::uuid, 'Lenguado', 'Llenguado', 'Sole', 'pescados', NULL, true, NULL, NULL, 4, NULL, NULL, NULL, true);                                                                    |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('6ca56151-310d-4c71-bc43-2d5127d60a21'::uuid, 'Gallo', 'Gall', 'Megrim', 'pescados', NULL, true, NULL, NULL, 5, NULL, NULL, NULL, true);                                                                          |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('dc666e26-a495-4bf8-8573-90d23bfb6df7'::uuid, 'Centolla', 'Centolla', 'Spider Crab', 'pescados', NULL, true, NULL, NULL, 6, NULL, NULL, NULL, true);                                                              |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('a2a497eb-bc43-4f01-83f0-97db3c2d6397'::uuid, 'Bogavante', 'Llagosta', 'Lobster', 'pescados', NULL, true, NULL, NULL, 7, NULL, NULL, NULL, true);                                                                 |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('367a6860-8c5a-4345-b787-99642a8c308f'::uuid, 'Alubias', 'Mongetes', 'White Beans', 'platos_calientes', 30.00, false, NULL, NULL, 1, 'con Almejas o Pulpo', 'amb Cloïsses o Pop', 'with Clams or Octopus', true); |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('9c63bd84-0edf-47f7-a2c1-e2f7894088b4'::uuid, 'Caldo Gallego', 'Brou Gallec', 'Galician Broth', 'platos_calientes', 7.00, false, NULL, NULL, 2, NULL, NULL, NULL, true);                                          |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('c8340a19-ed1f-4a35-8f8e-37d64916ede6'::uuid, 'Callos', 'Callos', 'Tripe Stew', 'platos_calientes', 16.00, false, NULL, NULL, 3, NULL, NULL, NULL, true);                                                         |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('de7a641a-bb46-42eb-b01d-21b8268b3808'::uuid, 'Filloas', 'Filloas', 'Filloas (Galician Crepes)', 'postres', 8.00, false, NULL, NULL, 1, NULL, NULL, NULL, true);                                                  |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('fb73acaf-c693-4306-8bef-092c7ac52055'::uuid, 'Cañitas', 'Canyetes', 'Cañitas', 'postres', 8.00, false, NULL, NULL, 2, NULL, NULL, NULL, true);                                                                   |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('d7427c30-ddb0-4b04-89aa-a9d5e46f643d'::uuid, 'Queso Arzua con Membrillo', 'Formatge Arzua amb Codony', 'Arzua Cheese with Quince', 'postres', 8.00, false, NULL, NULL, 3, NULL, NULL, NULL, true);               |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('b184dd19-a88f-4ad8-9489-c0f157641ec9'::uuid, 'Tarta de Santiago', 'Pastís de Santiago', 'Santiago Cake', 'postres', 8.00, false, NULL, NULL, 4, NULL, NULL, NULL, true);                                         |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('f3ce829e-29ac-494d-b529-86b69d8b6fcb'::uuid, 'Tarta de Queso', 'Pastís de Formatge', 'Cheesecake', 'postres', 8.00, false, NULL, NULL, 5, NULL, NULL, NULL, true);                                               |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('43f128a9-e1a5-4ceb-b46d-60d871b4c900'::uuid, 'Merayo', NULL, NULL, 'vino_blanco', 17.00, false, 'Godello', NULL, 1, NULL, NULL, NULL, true);                                                                     |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('47a0e87b-41d6-41cf-840a-8cb07bade461'::uuid, 'Polvorete', NULL, NULL, 'vino_blanco', 25.00, false, 'Godello', NULL, 2, NULL, NULL, NULL, true);                                                                  |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('8d479d0e-379d-4cce-b4c6-ec7cdbec9e9f'::uuid, 'La Gineta', NULL, NULL, 'vino_blanco', 30.00, false, 'Godello', NULL, 3, NULL, NULL, NULL, true);                                                                  |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('45abe02f-e5ce-4e00-94a0-e430f88cfcd5'::uuid, 'La Revelia', NULL, NULL, 'vino_blanco', 61.00, false, 'Godello', NULL, 4, NULL, NULL, NULL, true);                                                                 |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('eaf1032d-ae55-4ab0-806b-e16d663cc469'::uuid, 'Pazo Serantellos', NULL, NULL, 'vino_blanco', 17.00, false, 'Albariño', NULL, 5, NULL, NULL, NULL, true);                                                          |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('0039c5c2-ef93-4859-8bca-f9d251320e38'::uuid, 'Pazo Cilleiro', NULL, NULL, 'vino_blanco', 21.00, false, 'Albariño', NULL, 6, NULL, NULL, NULL, true);                                                             |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('51b2f203-6b1e-4515-b2bc-9e8973902588'::uuid, 'Viña Almirante', NULL, NULL, 'vino_blanco', 22.00, false, 'Albariño', NULL, 7, NULL, NULL, NULL, true);                                                            |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('2bfeaf68-cd21-40bf-a03d-893c58d81e41'::uuid, 'Pazo Baion', NULL, NULL, 'vino_blanco', 35.00, false, 'Albariño', NULL, 8, NULL, NULL, NULL, true);                                                                |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('c8bbde2f-c0ef-4d45-8829-796dfc531855'::uuid, 'Terras Vellas', NULL, NULL, 'vino_blanco', 36.00, false, 'Albariño', NULL, 9, NULL, NULL, NULL, true);                                                             |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('c4b71707-7e09-4453-b8b4-2cddfc66b701'::uuid, 'Santiago Roma', NULL, NULL, 'vino_blanco', 30.00, false, 'Albariño', NULL, 10, NULL, NULL, NULL, true);                                                            |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('3d638605-7473-498e-82aa-b02f4f6afbbf'::uuid, 'Pazo Señorans', NULL, NULL, 'vino_blanco', 40.00, false, 'Albariño', NULL, 11, NULL, NULL, NULL, true);                                                            |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('bb507d7a-d9c2-4176-8fd6-1be29ca26689'::uuid, 'Pazo de Rubianes', NULL, NULL, 'vino_blanco', 46.00, false, 'Albariño', NULL, 12, NULL, NULL, NULL, true);                                                         |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('5eb4c68a-47bb-46fd-a0b5-8290114b52c5'::uuid, 'Castillo de la Mota', NULL, NULL, 'vino_blanco', 12.00, false, 'Verdejo', NULL, 13, NULL, NULL, NULL, true);                                                       |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('19b39e96-2b90-438d-ac55-8fb3ed3550ca'::uuid, 'Dominio de la Granadilla', NULL, NULL, 'vino_blanco', 21.00, false, 'Verdejo', NULL, 14, NULL, NULL, NULL, true);                                                  |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('3594b666-6fb2-4bfe-9251-19b4309ac271'::uuid, 'Pujanza', NULL, NULL, 'vino_tinto', 29.00, false, NULL, NULL, 1, NULL, NULL, NULL, true);                                                                          |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('506e8bfb-de8c-410e-88ec-764bc641bb2c'::uuid, 'Ponte da Boga', NULL, NULL, 'vino_tinto', 31.00, false, NULL, NULL, 2, NULL, NULL, NULL, true);                                                                    |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('7646b6ce-8ed2-4835-a12c-3834f83830c3'::uuid, 'Emilio Moro 50cl', NULL, NULL, 'vino_tinto', 34.00, false, NULL, NULL, 3, NULL, NULL, NULL, true);                                                                 |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('19a3649b-afe2-4304-bbb5-9926c54aebdf'::uuid, 'Viña Sastre', NULL, NULL, 'vino_tinto', 65.00, false, NULL, NULL, 4, NULL, NULL, NULL, true);                                                                      |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('ff0c9bf0-1024-4917-8e33-9b77788494c9'::uuid, 'Torre Albéniz', NULL, NULL, 'vino_tinto', 65.00, false, NULL, NULL, 5, NULL, NULL, NULL, true);                                                                    |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('4d742761-f987-4867-86dc-aecda2a08627'::uuid, 'Tomás Postigo', NULL, NULL, 'vino_tinto', 78.00, false, NULL, NULL, 6, NULL, NULL, NULL, true);                                                                    |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('cba8d3e6-30e5-44f5-b310-1452dfef3075'::uuid, 'Torremilanos', NULL, NULL, 'vino_tinto', 65.00, false, NULL, NULL, 7, NULL, NULL, NULL, true);                                                                     |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('6ce8dd73-dffd-4f4e-a782-5a413751e52b'::uuid, 'Arzuaga Crianza', NULL, NULL, 'vino_tinto', 53.00, false, NULL, NULL, 8, NULL, NULL, NULL, true);                                                                  |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('7e0b4b36-6425-46fb-9ef2-4a627e148a5d'::uuid, 'Marques de Vargas', NULL, NULL, 'vino_tinto', 40.00, false, NULL, NULL, 9, NULL, NULL, NULL, true);                                                                |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('abcf1f31-491b-46b1-884f-be4f4b136ee3'::uuid, 'Pago de Carraovejas', NULL, NULL, 'vino_tinto', 78.00, false, NULL, NULL, 10, NULL, NULL, NULL, true);                                                             |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('3f7d86ea-a785-426e-bc4d-ae63eaf265f7'::uuid, 'La Rioja Alta 904', NULL, NULL, 'vino_tinto', 130.00, false, NULL, NULL, 11, NULL, NULL, NULL, true);                                                              |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('406ddc90-f2da-4599-bb2b-8060055109bd'::uuid, 'Pintia Vega Sicilia', NULL, NULL, 'vino_tinto', 95.00, false, NULL, NULL, 12, NULL, NULL, NULL, true);                                                             |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('3dd553f2-c78d-49dc-90b3-3be683610c85'::uuid, 'Alion Vega Sicilia', NULL, NULL, 'vino_tinto', 150.00, false, NULL, NULL, 13, NULL, NULL, NULL, true);                                                             |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('50976311-fc32-4713-bee8-11f354c6b63c'::uuid, 'Valbuena 5º 2019', NULL, NULL, 'vino_tinto', 180.00, false, NULL, NULL, 14, NULL, NULL, NULL, true);                                                               |
| INSERT INTO menu_items (id, nombre_es, nombre_ca, nombre_en, categoria, precio, precio_mercado, subcategoria, unidad, orden, descripcion_es, descripcion_ca, descripcion_en, disponible) VALUES ('d5e706a7-171d-4b7d-bf0c-977a941bcf3d'::uuid, 'Vega Sicilia Único', NULL, NULL, 'vino_tinto', 450.00, false, NULL, NULL, 15, NULL, NULL, NULL, true);                                                             |
|                                                                                                                                                                                                                                                                                                                                                                                                                    |
| -- SUBCATEGORIAS VINOS                                                                                                                                                                                                                                                                                                                                                                                             |
| INSERT INTO subcategorias_vinos (id, nombre, categoria_padre, orden, disponible) VALUES ('4f8878f1-500c-4cc4-a6e4-d6a04d183544'::uuid, 'Godello', 'vino_blanco', 1, true);                                                                                                                                                                                                                                         |
| INSERT INTO subcategorias_vinos (id, nombre, categoria_padre, orden, disponible) VALUES ('eac02a96-d4de-423f-b024-7b4cb991ef0f'::uuid, 'Albariño', 'vino_blanco', 2, true);                                                                                                                                                                                                                                        |
| INSERT INTO subcategorias_vinos (id, nombre, categoria_padre, orden, disponible) VALUES ('b0c3cb95-4be4-48d5-bde4-219f58a1bcf2'::uuid, 'Verdejo', 'vino_blanco', 3, true);                                                                                                                                                                                                                                         |